### ISSUE TITLE
TimeZonesOfLocale should return names in alphabetical order

### ISSUE THREAD

**Issue by anba** [tc39/proposal-intl-locale-info#28]
From <https://tc39.es/proposal-intl-locale-info/#sec-time-zones-of-locale>:
> Let list be a List of 1 or more time zone identifiers, which must be String values indicating a Zone or Link name of the IANA Time Zone Database, sorted in descending preference of those in common use in region.

In addition to the issue mentioned in #26, `TimeZonesOfLocale` should be changed to require that the names are sorted alphabetically, because there's no clear preference order for time zones and alphabetical order matches ICU.

**Comment by FrankYFTang** [comment]
fixed in #37
