### ISSUE TITLE
Missing standard preamble for abstract operations

### ISSUE THREAD

**Issue by anba** [tc39/proposal-intl-locale-info#40]
The new abstract operations are missing preambles. There should be at least one of:

> When the OP_NAME abstract operation is called with arguments ARG1, ARG2, and ARG3, it performs the following steps: 

or:

> When the OP_NAME abstract operation is called with arguments ARG1, ARG2, and ARG3, the following steps are taken:

**Comment by FrankYFTang** [comment]
Fixed by #42
