### ISSUE TITLE
Change CharacterDirectionOfLocale and WeekInfoOfLocale to receive an Intl.Locale object?

### ISSUE THREAD

**Issue by anba** [tc39/proposal-intl-locale-info#41]
The other abstract operations are all accepting `Intl.Locale` objects, only `CharacterDirectionOfLocale` and `WeekInfoOfLocale` receive the locale-id as a String value. Maybe worth making this consistent throughout the proposal?

**Comment by FrankYFTang** [comment]
closed by #42
