### ISSUE TITLE
[[Weekend]] ordering

### ISSUE THREAD

**Issue by Constellation** [tc39/proposal-intl-locale-info#51]
I've checked https://github.com/tc39/proposal-intl-locale-info/commit/afb1e269dd698476a2514129235cdad88af60e6f and I think the spec does not define the ordering of days in `[[Weekend]]`. Like, when Saturday and Sunday are weekend, it is possible that weekend array becomes `[7, 6]`.

It is good if we specify that numbers in this array is sorted via `%Array.prototype.sort%`.

**Comment by Constellation** [comment]
CC @FrankYFTang what do you think of?

**Comment by FrankYFTang** [comment]
Make sense. Let me work on that.
