### ISSUE TITLE
CharacterDirectionOfLocale doesn't handle top-to-bottom and bottom-to-top scripts

### ISSUE THREAD

**Issue by anba** [tc39/proposal-intl-locale-info#52]
[CharacterDirectionOfLocale](https://tc39.es/proposal-intl-locale-info/#sec-character-direction-of-locale) mentions `characterOrder` from [UTS 35 layout elements](https://unicode.org/reports/tr35/tr35-general.html#Layout_Elements), but only handles the left-to-right and right-to-left cases. It should also handle the top-to-bottom and bottom-to-top cases allowed in UTS 35 for the `characterOrder` element:
> If the value of lineOrder is one of the vertical values, then the value of characterOrder must be one of the horizontal values, and vice versa. 

cc @jfkthame and @zbraniecki

**Comment by FrankYFTang** [comment]
Dup of #59 See the conclusion there.
