### ISSUE TITLE
Intl.Locale.prototype.textInfo is missing "lineOrder" information

### ISSUE THREAD

**Issue by anba** [tc39/proposal-intl-locale-info#54]
[Intl.Locale.prototype.textInfo](https://tc39.es/proposal-intl-locale-info/#sec-Intl.Locale.prototype.textInfo) only returns the `characterOrder`, cf. [CharacterDirectionOfLocale](https://tc39.es/proposal-intl-locale-info/#sec-character-direction-of-locale), but [UTS 35 layout elements](https://unicode.org/reports/tr35/tr35-general.html#Layout_Elements) also defines `lineOrder`.

For example the `characterOrder` for the locale "mn-Mong" is "top-to-bottom" and its `lineOrder` is "left-to-right". Also see <https://en.wikipedia.org/wiki/Mongolian_script>.

cc @jfkthame and @zbraniecki

**Comment by FrankYFTang** [comment]
See https://github.com/tc39/proposal-intl-locale-info/issues/59
